export interface VocabularyObject {
  word_id: string; // e.g., 'subtle_1715971108'
  raw_text: string; // The original word/phrase saved by user
  lemma: string; // The root form generated by compromise.js
  vietnamese_meaning: string; // Translated Vietnamese meaning
  type: string; // 'word' | 'phrase' | 'collocation'
  current_streak: number; // 0 to 10 (SRS stage)
  next_review_time: string; // ISO 8601 Datetime string
  status: 'ready_to_review' | 'cooling';
  last_updated: string; // ISO 8601 Datetime string
  [key: string]: any; // Allow extending with custom/old fields dynamically
}

/**
 * Gracefully upgrades and extends old data objects to the new SRS VocabularyObject schema.
 * This preserves all existing fields on the object rather than resetting them, supporting
 * custom migration scripts or custom fields the user may have created.
 */
export function ensureSchema(wordObj: any, computedLemma?: string): VocabularyObject {
  if (!wordObj) return wordObj;

  // Clone to avoid direct mutation of shared state
  const updated = { ...wordObj };

  // 1. Ensure word_id exists (use existing or fallback)
  if (!updated.word_id) {
    const cleanWord = (updated.word || updated.raw_text || '').toLowerCase().trim();
    updated.word_id = cleanWord ? `${cleanWord}_${Math.floor(Date.now() / 1000)}` : `word_${Math.floor(Date.now() / 1000)}`;
  }

  // 2. Ensure raw_text exists
  if (!updated.raw_text) {
    updated.raw_text = updated.word || '';
  }

  // 3. Ensure lemma exists (root form)
  if (!updated.lemma) {
    updated.lemma = computedLemma || (updated.word || updated.raw_text || '').toLowerCase().trim();
  }

  // 4. Ensure vietnamese_meaning is present (map old meaning or fallback)
  if (updated.vietnamese_meaning === undefined) {
    updated.vietnamese_meaning = updated.meaning || 'Không tìm thấy nghĩa.';
  }

  // 5. Ensure type is categorized
  if (!updated.type) {
    const text = updated.raw_text || '';
    updated.type = text.trim().includes(' ') ? 'phrase' : 'word';
  }

  // 6. Ensure current_streak is defined
  if (updated.current_streak === undefined) {
    updated.current_streak = 0;
  }

  // 7. Ensure next_review_time is set
  if (!updated.next_review_time) {
    updated.next_review_time = new Date().toISOString();
  }

  // 8. Map old status or ensure correct new status format
  if (!updated.status || updated.status === 1 || updated.status === 0 || typeof updated.status === 'number') {
    // If it was marked as active (1), let's set it to 'ready_to_review' so the user can study it
    updated.status = 'ready_to_review';
  }

  // 9. Ensure last_updated timestamp exists
  if (!updated.last_updated) {
    if (updated.updatedAt && updated.updatedAt.seconds) {
      updated.last_updated = new Date(updated.updatedAt.seconds * 1000).toISOString();
    } else {
      updated.last_updated = new Date().toISOString();
    }
  }

  return updated as VocabularyObject;
}

/**
 * Calculates the next review time and streak adjustments for a 10-step Spaced Repetition System.
 * Returns the modified streak, next review timestamp, and sets the status to 'cooling'.
 */
export function calculateNextReview(current_streak: number, isCorrect: boolean): {
  current_streak: number;
  next_review_time: string;
  status: 'cooling';
} {
  let newStreak = current_streak;
  const nextReviewTime = new Date();

  if (isCorrect) {
    // Increment streak by 1, capped at 10
    newStreak = Math.min(10, current_streak + 1);

    // SRS Streak Interval Matrix (in minutes)
    let minutesToAdd = 0;
    switch (newStreak) {
      case 1: minutesToAdd = 30; break;               // +30 mins
      case 2: minutesToAdd = 2 * 60; break;            // +2 hours
      case 3: minutesToAdd = 4 * 60; break;            // +4 hours
      case 4: minutesToAdd = 12 * 60; break;           // +12 hours
      case 5: minutesToAdd = 24 * 60; break;           // +24 hours (1 day)
      case 6: minutesToAdd = 48 * 60; break;           // +48 hours (2 days)
      case 7: minutesToAdd = 72 * 60; break;           // +72 hours (3 days)
      case 8: minutesToAdd = 120 * 60; break;          // +120 hours (5 days)
      case 9: minutesToAdd = 168 * 60; break;          // +168 hours (7 days)
      case 10: minutesToAdd = 336 * 60; break;         // +336 hours (14 days)
      default: minutesToAdd = 30;
    }
    nextReviewTime.setMinutes(nextReviewTime.getMinutes() + minutesToAdd);
  } else {
    // Decrement streak by 1, floored at 0
    newStreak = Math.max(0, current_streak - 1);
    // Allow re-testing soon (+5 minutes)
    nextReviewTime.setMinutes(nextReviewTime.getMinutes() + 5);
  }

  return {
    current_streak: newStreak,
    next_review_time: nextReviewTime.toISOString(),
    status: 'cooling'
  };
}
